---

#### Configuration ####

- name: copy VITAM transport config file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/vitam_transport.conf
    owner: root
    mode: 0644
  when: 
    - groups['hosts_logstash']|length > 0
    - consul_disabled is not defined or consul_disabled |lower != "true"
  notify:
    - restart rsyslog

- name: Ensure service is started
  service:
    name: "rsyslog"
    state: started
