---
## Variables internes au rôle ; à ne pas surcharger par des variables plus globales
consul_service: "vitam-{{ consul_component }}"

consul_folder_log: "{{ vitam_defaults.folder.root_path }}/log/{{ consul_component }}"
consul_folder_data: "{{ vitam_defaults.folder.root_path }}/data/{{ consul_component }}"
