---
# tasks file for topbeat
- name: Ensure old topbeat package is absent
  package:
    name: topbeat
    state: absent

- name: install metricbeat package
  package:
    name: metricbeat
    state: latest

- name: apply metricbeat configuration
  template:
    src: metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    mode: 0644

- name: Upload dashboards zip file
  copy:
    src: "beats-dashboards-{{ beats_version }}.zip"
    dest: /tmp/beats-dashboards-{{ beats_version }}.zip


# OMA: needs more testing ; when recreating, ... Needs Internet access !!!
- name: import metricbeat dashboard into kibana
  shell: /usr/share/metricbeat/scripts/import_dashboards -file /tmp/beats-dashboards-{{ beats_version }}.zip -es http://{{ elasticsearch.log.host }}:{{ elasticsearch.log.port_http }}
  run_once: true
  when: "{{ (groups['hosts-kibana-log'] | length) > 0}}"
  delegate_to: "{{groups['hosts-kibana-log'][0]}}"
  retries: 5
  delay: 30
  register: result
  until: result.rc == 0
  notify:
    - restart kibana

- name: restart metricbeat
  service:
    name: metricbeat
    state: restarted
    enabled: true
