---
mongo_tmp_path:  '{{ vitam_defaults.folder.root_path }}/tmp/mongoc'
mongo_config_path:  '{{ vitam_defaults.folder.root_path }}/conf/mongoc'
mongo_db_path:      '{{ vitam_defaults.folder.root_path }}/data/mongoc/db'
