---
# KWA review : replace cron call by a systemd timer task ?
#  Pro : no external dependencies, kept in systemd
#  Pro/Con : everything in https://wiki.archlinux.org/index.php/Systemd/Timers#As_a_cron_replacement
#  Con : not well-known by sysadmin
#  Con : may be useless, as job scheduling inside Vitam may be delegated to a dedicated component (ihm-technical-administration)

# tasks file for engine-external
- name: ensure cronie (for crontab) is installed
  package:
    name: cronie
    state: present
  when: ansible_distribution == "CentOS"

- name: ensure cron (for crontab) is installed
  package:
    name: cron
    state: present
  when: ansible_distribution == "Debian"

- name: ensure script belongs to vitam
  file:
    path: "/vitam/script/logbook/launchTraceability.sh"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: 0750

- name: create cron entry for secure logbook operations
  cron:
    name: "Secure logbook operations"
    minute: "1"
    hour: "0-23"
    user: "{{ vitam_defaults.users.vitam }}"
    job: "/vitam/script/logbook/launchTraceability.sh >> /vitam/log/logbook/secure_logbook.log 2>&1"
  run_once: yes
  delegate_to: "{{ groups['hosts-logbook'] | last }}"

- name: add logrotate conf for secure logbook operations
  copy:
    src: "vitam_secure_logbook"
    dest: "/etc/logrotate.d/vitam_secure_logbook"
    owner: "root"
    group: "root"
    mode: "644"
