---

# Backports are need for openjdk8 & clamav
- name: "check {{ ansible_distribution_release }}-backports repo are present"
  apt_repository:
    repo: "{{ item }}"
    state: present
  with_items:
    - "deb http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
    - "deb-src http://ftp.debian.org/debian {{ ansible_distribution_release }}-backports main"
    - "deb http://deb.debian.org/debian/ stretch main" # necessary to properly install mongoDB
  when: disable_internet_repositories_install == false

- name: run apt-update
  apt:
    update_cache: yes
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
  tags:
    - update_package_vitam

- name: Make sure acl package is installed (for setfacl usage with become_user)
  package:
    name: acl
    state: present
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"
