---
- name: archive troubleshoot
  archive:
      path: "{{ inventory_dir }}/troubleshoot/"
      dest: "{{ inventory_dir }}/troubleshoot.zip"
      remove: yes
      format: zip
  delegate_to: localhost
  run_once: true

- name: remove troubleshoot directory
  file:
    path: "{{ inventory_dir }}/troubleshoot/"
    state: absent
  delegate_to: localhost
  run_once: true

- name: display post install message
  debug:
    msg: "Please send generated {{ inventory_dir }}/troubleshoot.zip file by mail to Vitam support"
  delegate_to: localhost
  run_once: true
