---
- name: Install Consul package
  package:
    name: "{{consul_service}}"
    state: latest
  notify:
      - restart consul

- name: Enable consul service
  service:
    name: "{{consul_service}}"
    enabled: true
  notify:
      - restart consul

#### Configuration ####

- name: Check that the consul directories exist
  file:
    path: "{{vitam_folder_root}}/{{ item }}/{{consul_component}}"
    state: directory
    owner: "{{ vitam_user}}"
    group: "{{ vitam_group }}"
    mode: "0750"
  with_items:
    - app
    - bin
    - conf
    - lib
    - log
    - data
    - tmp
  notify:
      - restart consul

- name: Deploy consul common configuration files
  template:
    src: "{{item}}.j2"
    dest: "{{consul_folder_conf}}/{{item}}"
    owner: "{{ vitam_user}}"
    group: "{{ vitam_group }}"
    mode: "{{vitam_conf_permission}}"
  with_items:
    - "consul.json"
  notify:
      - reload consul

# Ensure that the installation is complete and consul up before setting up the system-wide dns resolver...
- meta: flush_handlers

- name: Ensure service is started
  service:
    name: "{{consul_service}}"
    state: started

# Changing the resolv.conf doesn't work into a docker container...
- name: Add consul nameserver to resolv.conf
  blockinfile:
    backup: yes
    dest: /etc/resolv.conf
    insertbefore: BOF # necessary or this entry won't be asked
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      nameserver 127.0.0.1
  when: "inventory_hostname != 'localhost'"
