---

vitam:
    ihm_recette:
        vitam_component: ihm-recette
        host: "ihm-recette.service.{{ consul_domain }}"
        port_service: 8445
        port_admin: 28204
        baseurl: /ihm-recette
        static_content: "{{ vitam_defaults.folder.root_path }}/app/ihm-recette"
        baseuri: "ihm-recette"
        secure_mode:
            - authc
        https_enabled: true
        secret_platform: "false"
        cluster_name: "{{ elasticsearch.data.cluster_name }}"
        session_timeout: 1800000
        secure_cookie: true
        use_proxy_to_clone_tests: "yes"
        elasticsearch_mapping_dir: "{{ vitam_defaults.folder.root_path }}/conf/ihm-recette/mapping"
    library:
        vitam_component: library
        host: "library.service.{{ consul_domain }}"
        port_service: 8090
        port_admin: 28090
        baseuri: "doc"
        https_enabled: false
        secret_platform: "false"
        consul_business_check: 30 # value in seconds
        consul_admin_check: 30 # value in seconds

tenant_to_clean_before_tnr: ["0","1"]

# Period units in seconds
metricbeat:
    enabled: false
    system:
        period: 10
    mongodb:
        period: 10
    elasticsearch:
        period: 10

packetbeat:
    enabled: false

browser:
    enabled: false

docker_opts:
    registry_httponly: yes
    vitam_docker_tag: latest

gatling_install: false
docker_install: true # whether or not install docker & docker images
