---
# tasks file for cerebro
- name: Install java-1.8.0 (prerequisite for cerebro) only when CentOS
  yum:
    name: java-1.8.0
    state: latest
  when: ansible_os_family == "RedHat"
  notify:
    - restart cerebro

- name: install openjdk from jessie-backports (prerequisite for cerebro) only when Debian
  apt:
    name: "{{ item }}"
    state: latest
    default_release: jessie-backports
  with_items:
    - ca-certificates-java
    - openjdk-8-jre-headless
  when: ansible_os_family == "Debian"
  notify:
    - restart cerebro

- name: install vitam-elasticsearch-cerebro package
  package:
    name: vitam-elasticsearch-cerebro
    state: latest
  notify:
    - restart cerebro

- name: aply custom configuration
  template:
    src: application.conf.j2
    dest: "{{ vitam_defaults.folder.root_path }}/conf/cerebro/application.conf"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.folder_permission }}"
  notify:
    - restart cerebro

- name: Add vitam-elasticsearch-cerebro autostart at boot
  service:
    name: "vitam-elasticsearch-cerebro"
    enabled: yes
  notify:
    - restart cerebro

- name: Ensure consul config dir is OK
  file:
    path: "{{ consul_folder_conf }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"

- name: Deploy consul agent service declaration for cerebro service
  template:
    src: "service-componentid.json.j2"
    dest: "{{ consul_folder_conf }}/service-cerebro.json"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  tags:
    - consul_conf
  notify:
   - reload consul configuration

- name: Ensure consul service is started
  service:
    name: "vitam-consul"
    state: started
