---

- name: Compute the mongos server list
  set_fact: mongos_item="{{ item }}"
  when:
    - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
  with_items:
    - "{{ groups[mongos] }}"
  register: mongos_result
  tags:
    - update_mongodb_configuration

- name: make a list from the result
  set_fact:
    mongos_list: "{{ mongos_result.results | remove_skipped_servers | map(attribute='ansible_facts.mongos_item') | list }}"
  when: "inventory_hostname not in single_vm_hostnames"
  tags:
    - update_mongodb_configuration

- name: make a list from the result (localhost deploy)
  set_fact:
    mongos_list: "{{ single_vm_hostnames }}"
  when: "inventory_hostname in single_vm_hostnames"
  tags:
    - update_mongodb_configuration

- block:

    # Make sure the service is open (mongos listening on 27017)
    # TODO: put the timeout in global variable (timeout to wait for mongo to be open)
    - name: Wait for the service port to be open
      wait_for: host={{ ip_service }} port={{ mongodb.mongos_port }} timeout="{{ vitam_defaults.services.start_timeout }}"
      tags:
        - update_mongodb_configuration

    # Detect if authentication is enabled

    - name: Check if authent is enabled
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet --eval 'db.help()'"
      register: mongo_authent_enabled
      failed_when: false
      no_log: "{{ hide_passwords_during_deploy }}"
      tags:
        - update_mongodb_configuration

    # Set mongo_no_auth facts

    - name: Set default mongo facts
      set_fact:
        mongo_credentials: ""
        mongo_no_auth: false
      tags:
        - update_mongodb_configuration

    - name: Set mongo_no_auth fact to true
      set_fact:
        mongo_no_auth: true
      when: "mongo_authent_enabled.rc != 0"
      tags:
        - update_mongodb_configuration

    # When authentication is required, we set mongodb admin credentials
    - name: Set mongodb authentication credentials
      set_fact:
        mongo_credentials: " -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet"
      when: "mongo_authent_enabled.rc == 0"
      no_log: "{{ hide_passwords_during_deploy }}"
      tags:
        - update_mongodb_configuration

    # Copy the mongodb scripts

    - name: Copy the database scripts files for mongo-data
      template:
        src: "{{ item }}"
        dest: "{{ vitam_defaults.folder.root_path }}/app/mongos/{{ item | basename | regex_replace('\\.j2$') }}"
        owner: "{{ vitam_defaults.users.vitamdb }}"
        group: "{{ vitam_defaults.users.group }}"
        mode: "{{ vitam_defaults.folder.conf_permission }}"
      loop:
        - "mongo-data/enable-sharding.js.j2"
        - "mongo-data/init-identity-database.js.j2"
        - "mongo-data/init-logbook-database.js.j2"
        - "mongo-data/init-masterdata-database.js.j2"
        - "mongo-data/init-metadata-database.js.j2"
        - "mongo-data/init-report-database.js.j2"
        - "mongo-data/users-admin.js.j2"
        - "mongo-data/users-identity.js.j2"
        - "mongo-data/users-logbook.js.j2"
        - "mongo-data/users-masterdata.js.j2"
        - "mongo-data/users-metadata.js.j2"
        - "mongo-data/users-report.js.j2"
      when:
        - "mongo_cluster_name == 'mongo-data'"
      tags:
        - update_mongodb_configuration

    - name: Copy the database scripts files for collect module
      template:
        src: "{{ item }}"
        dest: "{{ vitam_defaults.folder.root_path }}/app/mongos/{{ item | basename | regex_replace('\\.j2$') }}"
        owner: "{{ vitam_defaults.users.vitamdb }}"
        group: "{{ vitam_defaults.users.group }}"
        mode: "{{ vitam_defaults.folder.conf_permission }}"
      loop:
        - "mongo-data/init-metadata-collect-database.js.j2"
        - "mongo-data/users-collect.js.j2"
        - "mongo-data/users-metadata-collect.js.j2"
      when: >
        mongo_cluster_name == 'mongo-data' and
        groups['hosts_collect'] | default([]) | length > 0 and
        groups['hosts_metadata_collect'] | default([]) | length > 0
      tags:
        - update_mongodb_configuration

    - name: Copy the database scripts files for mongo-offer
      template:
        src: "{{ item }}"
        dest: "{{ vitam_defaults.folder.root_path }}/app/mongos/{{ item | basename | regex_replace('\\.j2$') }}"
        owner: "{{ vitam_defaults.users.vitamdb }}"
        group: "{{ vitam_defaults.users.group }}"
        mode: "{{ vitam_defaults.folder.conf_permission }}"
      with_fileglob:
        - "{{ role_path }}/templates/mongo-offer/*"
      when:
        - "mongo_cluster_name != 'mongo-data'"
      tags:
        - update_mongodb_configuration

    # Enable sharding for specific databases and collections

    - name: Enable the sharding
      command: mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin {{ mongo_credentials }} {{ vitam_defaults.folder.root_path }}/app/mongos/enable-sharding.js
      no_log: "{{ hide_passwords_during_deploy }}"
      tags:
        - update_mongodb_configuration

    - name: Create the users
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin {{ mongo_credentials }} {{ vitam_defaults.folder.root_path }}/app/mongos/users-{{ item }}.js"
      with_items:
        - admin
        - logbook
        - masterdata
        - metadata
        - identity
        - report
      no_log: "{{ hide_passwords_during_deploy }}"
      when: "mongo_cluster_name == 'mongo-data'"
      tags:
        - update_mongodb_configuration

    - name: Create collect module user
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin {{ mongo_credentials }} {{ vitam_defaults.folder.root_path }}/app/mongos/users-{{ item }}.js"
      with_items:
        - collect
        - metadata-collect
      no_log: "{{ hide_passwords_during_deploy }}"
      when: >
        mongo_cluster_name == 'mongo-data' and
        groups['hosts_collect'] | default([]) | length > 0 and
        groups['hosts_metadata_collect'] | default([]) | length > 0
      tags:
        - update_mongodb_configuration

    - name: Create the users
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin {{ mongo_credentials }} {{ vitam_defaults.folder.root_path }}/app/mongos/users-{{ item }}.js"
      with_items:
        - admin
        - offer
      no_log: "{{ hide_passwords_during_deploy }}"
      when: "mongo_cluster_name != 'mongo-data'"
      tags:
        - update_mongodb_configuration

    # Activate security on mongo instances

    - name: Activate security on mongos instances
      blockinfile:
        dest: "{{ mongos_config_path }}/mongos.conf"
        insertafter: "# ansible managed security conf"
        block: |
          security:
            clusterAuthMode: keyFile
            keyFile: "{{ mongos_config_path }}/keyfile"
      delegate_to: "{{ item }}"
      when:
        - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items: "{{ groups[mongos] }}"
      tags:
        - update_mongodb_configuration

    - name: Activate security on mongod instances
      blockinfile:
        dest: "{{ mongod_config_path }}/mongod.conf"
        insertafter: "# ansible managed security conf"
        block: |
          security:
            authorization: enabled
            clusterAuthMode: keyFile
            keyFile: "{{ mongod_config_path }}/keyfile"
      delegate_to: "{{ item }}"
      when:
        - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items: "{{ groups[mongod] }}"
      tags:
        - update_mongodb_configuration

    - name: Activate security on mongoc instances
      blockinfile:
        dest: "{{ mongoc_config_path }}/mongoc.conf"
        insertafter: "# ansible managed security conf"
        block: |
          security:
            authorization: enabled
            clusterAuthMode: keyFile
            keyFile: "{{ mongoc_config_path }}/keyfile"
      delegate_to: "{{ item }}"
      when:
        - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items: "{{ groups[mongoc] }}"
      tags:
        - update_mongodb_configuration

    # Restart the mongo instances (to enable auth)

    - name: restart mongod
      service:
         name: vitam-mongod
         enabled: "{{ mongodb.at_boot | default(service_at_boot) }}"
         state: restarted
      delegate_to: "{{ item }}"
      when:
        - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items: "{{ groups[mongod] }}"
      tags:
        - update_mongodb_configuration

    - name: restart mongoc
      service:
         name: vitam-mongoc
         enabled: "{{ mongodb.at_boot | default(service_at_boot) }}"
         state: restarted
      delegate_to: "{{ item }}"
      when:
        - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items: "{{ groups[mongoc] }}"
      tags:
        - update_mongodb_configuration

    - name: restart mongos
      service:
         name: vitam-mongos
         enabled: "{{ mongodb.at_boot | default(service_at_boot) }}"
         state: restarted
      delegate_to: "{{ item }}"
      when:
        - "mongo_cluster_name == hostvars[item]['mongo_cluster_name']"
      with_items: "{{ groups[mongos] }}"
      tags:
        - update_mongodb_configuration

    # Make sure the service is open (mongos listening on 27017 by default)

    - name: Wait for the service port to be open
      wait_for: host={{ ip_service }} port={{ mongodb.mongos_port }} timeout="{{ vitam_defaults.services.start_timeout }}"
      tags:
        - update_mongodb_configuration

    # Initiate the databases (now we know that authentication is enabled)

    - name: Initiate the databases
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet {{ vitam_defaults.folder.root_path }}/app/mongos/init-{{ item }}-database.js"
      with_items:
        - logbook
        - masterdata
        - metadata
        - identity
        - report
      no_log: "{{ hide_passwords_during_deploy }}"
      when: "mongo_cluster_name == 'mongo-data'"
      tags:
        - update_mongodb_configuration

    - name: Initiate metadata-collect database
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet {{ vitam_defaults.folder.root_path }}/app/mongos/init-metadata-collect-database.js"
      no_log: "{{ hide_passwords_during_deploy }}"
      when: >
        mongo_cluster_name == 'mongo-data' and
        groups['hosts_metadata_collect'] | default([]) | length > 0
      tags:
        - update_mongodb_configuration

    - name: Initiate the databases
      command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet {{ vitam_defaults.folder.root_path }}/app/mongos/init-{{ item }}-database.js"
      with_items:
        - offer
        - tape-offer
      no_log: "{{ hide_passwords_during_deploy }}"
      when: "mongo_cluster_name != 'mongo-data'"
      tags:
        - update_mongodb_configuration

  when: mongos_list |last == inventory_hostname
