---
# Make sure the service is open (mongos listening on 27017)

# TODO: put the timeout in global variable (timeout to wait for mongo to be open)
- name: Wait for the service port to be open
  wait_for: port={{ mongodb.mongos_port }} timeout="{{ vitam_defaults.services.start_timeout }}"
  run_once: true

# Detect if authentication is enabled

- name: Check if authent is enabled
  command: "mongo localhost:{{ mongodb.mongos_port }}/admin -u {{mongoAdminUser}} -p {{mongoAdminPassword}} --quiet --eval 'db.help()'"
  run_once: true
  register: mongo_authent_enabled
  failed_when: false
  no_log: true

# Set mongo_no_auth facts

- name: Set default mongo facts
  set_fact:
    mongo_credentials: ""
    mongo_no_auth: false
  run_once: true

- name: Set mongo_no_auth fact to true
  set_fact:
    mongo_no_auth: true
  when: "mongo_authent_enabled.rc != 0"
  run_once: true

# When authentication is required, we set mongodb admin credentials
- name: Set mongodb authentication credentials
  set_fact:
    mongo_credentials: " -u {{mongoAdminUser}} -p {{mongoAdminPassword}} --quiet"
  when: "mongo_authent_enabled.rc == 0"
  no_log: true
  run_once: true

# Copy the mongodb scripts

- name: Copy the database scripts files
  template:
    src: "{{ item }}.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/app/mongos/{{ item }}"
    owner: "{{ vitam_defaults.users.vitamdb }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  with_items: "{{ lookup('pipe','find {{ role_path }}/templates/ -type f  -exec basename {} .j2 \\;').split('\n') }}"
  run_once: true

# Enable sharding for specific databases and collections

- name: Enable the sharding
  command: mongo localhost:{{ mongodb.mongos_port }}/admin {{mongo_credentials}} {{ vitam_defaults.folder.root_path }}/app/mongos/enable-sharding.js
  run_once: true
  no_log: true

# Initiate the databases and the related users
# FIXME: use mongodb_user module which is curently in extras modules -> need to install pymongo on mongodb servers

- name: Create the users
  command: "mongo localhost:{{ mongodb.mongos_port }}/admin {{mongo_credentials}} {{ vitam_defaults.folder.root_path }}/app/mongos/users-{{ item }}.js"
  run_once: true
  with_items:
    - admin
    - logbook
    - masterdata
    - metadata
    - identity
  no_log: true

# Activate security on mongo instances

# TODO: check if we can activate security by default and then create the users
#  (caution : it seems that we can only create one user while being anonymous after security enabling)
- name: Activate security on mongos instances
  blockinfile:
    dest: "{{ mongos_config_path }}/mongos.conf"
    insertafter: "# ansible managed security conf"
    block: |
      security:
        clusterAuthMode: keyFile
        keyFile: "{{ mongos_config_path }}/keyfile"
  delegate_to: "{{ item }}"
  with_items: "{{groups['mongos']}}"
  run_once: true

- name: Activate security on mongod instances
  blockinfile:
    dest: "{{ mongod_config_path }}/mongod.conf"
    insertafter: "# ansible managed security conf"
    block: |
      security:
        authorization: enabled
        clusterAuthMode: keyFile
        keyFile: "{{ mongod_config_path }}/keyfile"
  delegate_to: "{{ item }}"
  with_items: "{{groups['mongod']}}"
  run_once: true

- name: Activate security on mongoc instances
  blockinfile:
    dest: "{{ mongoc_config_path }}/mongoc.conf"
    insertafter: "# ansible managed security conf"
    block: |
      security:
        authorization: enabled
        clusterAuthMode: keyFile
        keyFile: "{{ mongoc_config_path }}/keyfile"
  delegate_to: "{{ item }}"
  with_items: "{{groups['mongoc']}}"
  run_once: true

# Restart the mongo instances (to enable auth)

- name: restart mongod
  service:
     name: vitam-mongod
     enabled: true
     state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{groups['mongod']}}"
  run_once: true

- name: restart mongoc
  service:
     name: vitam-mongoc
     enabled: true
     state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{groups['mongoc']}}"
  run_once: true

- name: restart mongos
  service:
     name: vitam-mongos
     enabled: true
     state: restarted
  delegate_to: "{{ item }}"
  with_items: "{{groups['mongos']}}"
  run_once: true

# Make sure the service is open (mongos listening on 27017)

- name: Wait for the service port to be open
  wait_for: port={{ mongodb.mongos_port }} timeout="{{ vitam_defaults.services.start_timeout }}"
  run_once: true

# Initiate the databases (now we know that authentication is enabled)

- name: Initiate the databases
  command: "mongo localhost:{{ mongodb.mongos_port }}/admin -u {{mongoAdminUser}} -p {{mongoAdminPassword}} --quiet {{ vitam_defaults.folder.root_path }}/app/mongos/init-{{ item }}-database.js"
  run_once: true
  with_items:
    - admin
    - logbook
    - masterdata
    - metadata
    - identity
  no_log: true
