---

- name: Ensure service is started 
  service:
    name: "vitam-metadata"
    state: started

- name: "Wait until service metadata is up"
  wait_for:
      host: "{{ hostvars[groups['hosts-metadata'][0]]['ip_admin'] }}"
      port: "{{ vitam.metadata.port_admin }}"
      state: "started"
      timeout: "{{ vitam_defaults.services.start_timeout }}"
  run_once: true

- name: graph + SEDA upgrade
  uri:
    method: POST
    status_code: 202,409
    url: "http://{{ hostvars[groups['hosts-metadata'][0]]['ip_admin'] }}:{{ vitam.metadata.port_admin }}/metadata/v1/migration"
    headers:
      Accept: application/json
    force_basic_auth: yes
    user: "{{ admin_basic_auth_user }}"
    password: "{{ admin_basic_auth_password }}"
  run_once: true


- name: check upgrade is finished
  command: "curl -I --silent -k -H \"Accept: application/json\"  http://{{ hostvars[groups['hosts-metadata'][0]]['ip_admin'] }}:{{ vitam.metadata.port_admin }}/metadata/v1/migration/status"
  register: result
  until: result.stdout.find("404 Not Found") != -1
  retries: "{{ nb_retries }}"
  delay: 60
  run_once: true

