---
# tasks file for topbeat
- name: install topbeat rpm
  yum:
    name: topbeat
    state: latest


- name: apply Topbeat configuration
  template:
    src: topbeat.yml.j2
    dest: /etc/topbeat/topbeat.yml
    owner: root
    mode: 0644

# OMA Commented curl -XDELETE 'http://{{vitam_log_host}}:{{elasticsearch_log_http_port}}/topbeat-*';
# OMA added ignore_errors due to stange things sometimes when redeploying
- name: force use topbeat index
  command: curl -XPUT 'http://{{elasticsearch_log_host}}:{{elasticsearch_log_http_port}}/_template/topbeat' -d@/etc/topbeat/topbeat.template.json
  ignore_errors: true
  notify:
    - restart kibana
  delegate_to: "{{groups['hosts-log-server'][0]}}"
  run_once: true

- name: load dashboards into Elasticsearch log .kibana index
  when: "{{ (groups['hosts-log-server'] | length) > 0}}"  
  run_once: true
  uri:
    url: 'http://{{elasticsearch_log_host}}:{{elasticsearch_log_http_port}}/.kibana/{{ item.split(".")[0] }}'
    method: PUT
    body: "{{ lookup('file', '{{role_path}}/files/kibana-metrics-configuration/{{item}}') }}"
    body_format: json
    status_code: 200, 201
  with_lines: find {{ search_dir }} {{ dashboard_dir }} {{ index_pattern_dir }} {{ visualization_dir }} -name '*.json' -type f | awk -F '/' '{print $(NF-1)"/"$NF}'
  vars:
    search_dir: "{{role_path}}/files/kibana-metrics-configuration/search"
    dashboard_dir: "{{role_path}}/files/kibana-metrics-configuration/dashboard"
    index_pattern_dir: "{{role_path}}/files/kibana-metrics-configuration/index-pattern"
    visualization_dir: "{{role_path}}/files/kibana-metrics-configuration/visualization"

- name: restart topbeat
  service:
    name: topbeat
    state: restarted
    enabled: true

  # TODO: change : virtualization_type is wrong here, we should assert if curator was indeed installed
- name: apply configuration files for curator
  template:
    src: "{{item}}.j2"
    dest: "{{curator_conf_dir}}/{{item}}"
    owner: logstash
  with_items:
    - "delete_index_topbeat.yml"
  delegate_to: "{{groups['hosts-log-server'][0]}}"
  run_once: true
  when: ansible_virtualization_type != 'docker'

- name: create root crontab entry
  run_once: true
  delegate_to : "{{groups['hosts-log-server'][0]}}"
  cron:
    name="curator purge on topbeat"
    minute="10"
    hour="0"
    user="root"
    job="/usr/bin/curator --config {{curator_conf_dir}}/curator.yml {{curator_conf_dir}}/delete_index_topbeat.yml"
  when: ansible_virtualization_type != 'docker'

