---
#####
# TODO : fixme, security-internal API was not backported in R7.5  
#####

# - name: Ensure service is started 
#   service:
#     name: "vitam-security-internal"
#     state: started

# - name: "Wait until service security-internal is up"
#   wait_for:
#       host: "{{ hostvars[groups['hosts-security-internal'][0]]['ip_admin'] }}"
#       port: "{{ vitam.security_internal.port_admin }}"
#       state: "started"
#       timeout: "{{ vitam_defaults.services.start_timeout }}"
#   run_once: true

# - name: Certificates upgrade
#   uri:
#     method: POST
#     status_code: 202,409
#     url: "http://{{ hostvars[groups['hosts-security-internal'][0]]['ip_admin'] }}:{{ vitam.security_internal.port_admin }}/v1/api/security/migration"
#     headers:
#       Accept: application/json
#     force_basic_auth: yes
#     user: "{{ admin_basic_auth_user }}"
#     password: "{{ admin_basic_auth_password }}"
#   run_once: true


# - name: Check upgrade is finished
#   command: "curl -I --silent -k -H \"Accept: application/json\"  http://{{ hostvars[groups['hosts-security-internal'][0]]['ip_admin'] }}:{{ vitam.security_internal.port_admin }}/v1/api/security/migration/status"
#   register: result
#   until: result.stdout.find("404 Not Found") != -1
#   retries: "{{ nb_retries }}"
#   delay: 60
#   run_once: true

- name: Copy the database scripts files
  template:
    src: "update-certificates.js.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/app/mongos/update-certificates.js"
    owner: "{{ vitam_defaults.users.vitamdb }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  when:
    - "mongo_cluster_name == 'mongo-data'"

- name: update contexts tenant directive directly in mongo
  command: "mongo {{ ip_service }}:{{ mongodb.mongos_port }}/admin -u {{ mongodb[mongo_cluster_name].admin.user }} -p {{ mongodb[mongo_cluster_name].admin.password }} --quiet {{ vitam_defaults.folder.root_path }}/app/mongos/update-certificates.js"
  when: "mongo_cluster_name == 'mongo-data'"
  run_once: true