---
mongoclient_root_url: "http://{{ip_admin}}"
mongoclient_port: 3000
#mongoclient_user: ""
#mongoclient_pwd: ""
mongoclient_confdb:
  host: localhost
  port: 27017
  name: mongoclient
#  user:
#  pwd:
mongoclient_confmail: {}
#  user:
#  pwd:
#  host:
#  port:
