---

prometheus_server_tmp_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/tmp/prometheus"
prometheus_server_config_path: "{{ vitam_defaults.folder.root_path | default('/vitam') }}/conf/prometheus"
prometheus_server_db_path:     "{{ vitam_defaults.folder.root_path | default('/vitam') }}/data/prometheus"
prometheus_server_app_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/app/prometheus"
prometheus_server_bin_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/bin/prometheus"
prometheus_server_log_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/log/prometheus"

service_at_boot: "{{ vitam_defaults.services.at_boot | default(false) }}"

