---
#### Installation ####
- name: Install vitam-node-exporter package
  package:
    name: vitam-node-exporter
    state: latest
  register: result
  retries: "{{ packages_install_retries_number | default(1) }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay | default(10) }}"
  notify: "prometheus-node-exporter - restart service"

#### Configuration ####
- name: Check that node_exporter directories exist
  file:
    path: "{{ vitam_defaults.folder.root_path | default('/vitam') }}/{{ item }}/node_exporter"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"
  with_items:
    - app
    - bin
    - conf
    - lib
    - log
    - data
    - tmp
  notify: "prometheus-node-exporter - restart service"

- name: Apply node_exporter sysconfig settings
  template:
    src: "node_exporter.j2"
    dest: "{{ prometheus_node_exporter_config_path }}/sysconfig/node_exporter"
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.conf_permission | default('0640') }}"
  tags:
    - update_node_exporter_configuration
  notify: "prometheus-node-exporter - restart service"

- name: Add directory for textfile_collector
  file:
    path: "{{ vitam_defaults.folder.root_path | default('/vitam') }}/data/node_exporter/textfile_collector"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"
  tags:
    - update_node_exporter_configuration

#### Consul configuration ####
- name: Ensure consul config dir is OK
  file:
    path: "{{ consul_folder_conf }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"

- name: Deploy consul agent service declaration
  template:
    src: "service-node-exporter.json.j2"
    dest: "{{ consul_folder_conf }}/service-node-exporter.json"
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.conf_permission | default('0640') }}"
  tags:
    - consul_conf
    - update_node_exporter_configuration
  notify: "prometheus-node-exporter - reload consul configuration"

# Ensure that the installation is complete
- meta: flush_handlers
  tags:
    - update_node_exporter_configuration

- name: Ensure vitam-node-exporter service is started
  service:
    name: vitam-node-exporter
    state: started
    enabled: "{{ prometheus.node_exporter.at_boot | default(service_at_boot) }}"

- name: Wait for node_exporter port {{ prometheus.node_exporter.port | default(9101) }} to be open
  wait_for:
    host: "{{ ip_admin }}"
    port: "{{ prometheus.node_exporter.port | default(9101) }}"
    state: "started"
    timeout: "{{ vitam_defaults.services.start_timeout | default(300) }}"
