---

- name: Remove vitam-node-exporter package
  package:
    name: vitam-node-exporter
    state: absent
  register: result
  retries: "{{ packages_install_retries_number | default(1) }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay | default(10) }}"

- name: Remove consul agent service declaration for node-exporter
  file:
    path: "{{ consul_folder_conf }}/service-node-exporter.json"
    state: absent
  tags:
    - consul_conf
    - update_node_exporter_configuration
  notify: "prometheus-node-exporter - reload consul configuration"
