---
# tasks file for rsyslog

- name: ensure rsyslog package is installed
  package:
    name: rsyslog
    state: latest
  notify:
    - restart rsyslog

- name: ensure service is started on boot && restart service
  service:
    name: rsyslog
    enabled: true
  notify:
    - restart rsyslog

#### Configuration ####

- name: copy VITAM transport config file
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.d/vitam_transport.conf
    owner: root
    mode: 0644
  when: groups['hosts-logstash']|length > 0
  notify:
    - restart rsyslog

- name: activate UDP in rsyslog
  replace:
    dest: /etc/rsyslog.conf
    regexp: '^#\$ModLoad imudp.*$'
    replace: "$ModLoad imudp"
  notify:
    - restart rsyslog

- name: activate port 514 in rsyslog
  replace:
    dest: /etc/rsyslog.conf
    regexp: '^#\$UDPServerRun 514.*$'
    replace: "$UDPServerRun 514"
  notify:
    - restart rsyslog

- name: Ensure service is started
  service:
    name: "rsyslog"
    state: started
