---

- block:

    - name: Get current ontologies if any
      uri:
        method: GET
        body: "{ \"$query\":{},\"$filter\":{},\"$projection\":{} }"
        status_code: 200
        url: "http://{{ hostvars[groups['hosts_functional_administration'][0]]['ip_admin'] }}:{{ vitam.functional_administration.port_admin }}/v1/admin/ontologies"
        body_format: "json"
      register: last_ontologies_response

    - name: Prepare ontology backup
      set_fact:
        last_ontologies: "{{ last_ontologies_response.json |regex_replace('\\$results', 'results') }}"
        backup_file_name: "ontology_backup_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}.json"

    - name: Backup ontology
      copy:
        content: "{{ last_ontologies.results }}"
        dest: "{{ vitam_defaults.folder.root_path }}/tmp/{{ vitam_struct.vitam_component }}/{{ backup_file_name }}"
        mode: 0775
        owner: "{{ vitam_defaults.users.vitam }}"
        group: "{{ vitam_defaults.users.group }}"

    - name: Fetch backup file from {{ vitam_struct.vitam_component }}
      fetch:
        src: "{{ vitam_defaults.folder.root_path }}/tmp/{{ vitam_struct.vitam_component }}/{{ backup_file_name }}"
        dest: "{{ inventory_dir }}/backups/{{ backup_file_name }}"
        flat: yes

    - name: Import/update Internal ontologies to functionnal-admin
      uri:
        method: POST
        body: "{{ lookup('file', '{{ inventory_dir }}/ontology/VitamOntology.json')}}"
        status_code: 200,201
        url: "http://{{ hostvars[groups['hosts_functional_administration'][0]]['ip_admin'] }}:{{ vitam.functional_administration.port_admin }}/v1/admin/ontologies"
        body_format: "json"
        timeout: "{{ vitam_defaults.services.api_long_call_timeout }}"
        headers:
          X-Tenant-Id: "{{ vitam_tenant_admin }}"
          
  run_once: true
