---
prometheus_node_exporter_tmp_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/tmp/node_exporter"
prometheus_node_exporter_config_path: "{{ vitam_defaults.folder.root_path | default('/vitam') }}/conf/node_exporter"
prometheus_node_exporter_db_path:     "{{ vitam_defaults.folder.root_path | default('/vitam') }}/data/node_exporter"
prometheus_node_exporter_app_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/app/node_exporter"
prometheus_node_exporter_bin_path:    "{{ vitam_defaults.folder.root_path | default('/vitam') }}/bin/node_exporter"

service_at_boot: "{{ vitam_defaults.services.at_boot | default(false) }}"
