---

- set_fact:
    cas: "Unit"

- name: reindexing ES for {{ cas }}
  uri:
    url: "http://{{ hostvars[groups['hosts_functional_administration'][0]]['ip_admin'] }}:{{ vitam.functional_administration.port_admin }}/adminmanagement/v1/reindex"
    method: POST
    headers:
      Connection: "keep-alive"
      X-Tenant-Id: "{{ vitam_tenant_admin }}"
    body: "[{\"collection\" : \"{{ cas }}\", \"tenants\" : {{ vitam_tenant_ids }}}]"
    body_format: "json"
    validate_certs: false
    return_content: yes
    status_code: 201, 202
    timeout: "36000"
  register: reindex
  run_once: true

- name: Modify json for {{ cas }}
  set_fact:
    reindexes: "{{ reindex.json |regex_replace('\\$results', 'results') }}"
  run_once: true
    
- name: re-aliasing ES for {{ cas }}
  uri:
    url: "http://{{ hostvars[groups['hosts_functional_administration'][0]]['ip_admin'] }}:{{ vitam.functional_administration.port_admin }}/adminmanagement/v1/alias"
    method: POST
    headers:
      Connection: "keep-alive"
      X-Tenant-Id: "{{ vitam_tenant_admin }}"
    body: "[{\"collection\" : \"{{ cas }}\", \"alias\" : \"{{ item.aliasName }}\", \"indexName\" : \"{{ item.indexName }}\"}]"
    body_format: "json"
    validate_certs: false
    return_content: yes
    #status_code: 201, 202
    timeout: "36000"
  with_items:
    - "{{ reindexes.results[0].OK }}"
  run_once: true