---
- name: Populate service facts
  service_facts:

# Logbook timers
- name: Make sure timers are stopped for {{ vitam_component }}
  systemd:
    name: "{{ item }}.timer"
    state: "stopped"
  loop: "{{ list_timers }}"

# Wait for the service to be stopped
- name: Wait for associated service to be stopped for {{ vitam_component }}
  wait_for_service:
    name: "{{ item }}.service"
    state: "stopped"
    timeout: "{{ vitam_defaults.services.stop_timeout }}"
  when: item + '.service' in ansible_facts.services
  loop: "{{ list_timers }}"

