---

- name: Install Consul rpm
  yum:
    name: "{{consul_service}}"
    state: latest

- name: Check that the consul directories exist
  file:
    path: "/vitam/{{ item }}/{{consul_component}}"
    state: directory
    owner: "{{ vitam_user}}"
    group: "{{ vitam_group }}"
    mode: "0750"
  with_items:
    - app
    - bin
    - conf
    - lib
    - log
    - data
    - tmp


- name: Deploy consul common configuration files
  template:
    src: "{{item}}.j2"
    dest: "{{consul_folder_conf}}/{{item}}"
    owner: "{{ vitam_user}}"
    group: "{{ vitam_group }}"
    mode: "{{vitam_conf_permission}}"
  with_items:
    - "consul.json"

- name: (re-)start consul
  service:
    name: "{{consul_service}}"
    enabled: true
  notify:
      - restart consul

# Ensure that the installation is complete and consul up before setting up the system-wide dns resolver...
- meta: flush_handlers

- name: add consul nameserver to resolv.conf
  blockinfile:
    backup: yes
    dest: /etc/resolv.conf
    insertbefore: BOF # necessary or this entry won't be asked
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: |
      nameserver 127.0.0.1
  when: ansible_virtualization_type != 'docker' # Changing the resolv.conf doesn't work into a docker container...
