---

- name: Install curl...
  package:
    name: curl
    state: present
  register: result
  retries: "{{ packages_install_retries_number }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay }}"

- name: Ensure computegraph.sh is absent
  file:
    path: "{{ vitam_defaults.folder.root_path }}/script/metadata/computegraph.sh"
    state: absent

- name: Copy the metadata reconstruction and log shipping and compute graph script
  template:
    src: "{{ item }}.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/script/metadata/{{ item }}"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.script_permission }}"
  with_items:
    - reconstruction.sh
    - storegraph.sh
    - computed_inherited_rules.sh
    - purge_dip.sh
    - reconstruction_payload.json

- name: Copy the metadata reconstruction conf
  template:
    src: "reconstruction.conf.j2"
    dest: "{{ vitam_defaults.folder.root_path }}/conf/metadata/reconstruction.conf"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  tags:
    - update_vitam_configuration

- name: Ensure vitam-metadata-reconstruction timer is stopped
  systemd:
    name: "vitam-metadata-reconstruction.timer"
    daemon_reload: "yes"
    enabled: "no"
    state: "stopped"
  when: ( primary_site | lower == "true" ) or
        ( inventory_hostname != groups["hosts_metadata"] | last )

- name: Ensure vitam-metadata-reconstruction timer is started
  systemd:
    name: "vitam-metadata-reconstruction.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( inventory_hostname == groups["hosts_metadata"] | last ) and
        ( primary_site | lower == "false" )



- name: Ensure vitam-metadata-store-graph timer is stopped
  systemd:
    name: "vitam-metadata-store-graph.timer"
    daemon_reload: "yes"
    enabled: "no"
    state: "stopped"
  when: ( primary_site | lower == "false" ) or
        ( inventory_hostname != groups["hosts_metadata"] | last )

- name: Ensure vitam-metadata-store-graph timer is started
  systemd:
    name: "vitam-metadata-store-graph.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( inventory_hostname == groups["hosts_metadata"] | last ) and
        ( primary_site | lower == "true" )

- name: Ensure vitam-metadata-computed-inherited-rules timer is stopped
  systemd:
    name: "vitam-metadata-computed-inherited-rules.timer"
    daemon_reload: "yes"
    enabled: "no"
    state: "stopped"
  when: ( primary_site | lower == "false" ) or
        ( inventory_hostname != groups["hosts_metadata"] | last )

- name: Ensure vitam-metadata-computed-inherited-rules timer is started
  systemd:
    name: "vitam-metadata-computed-inherited-rules.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( inventory_hostname == groups["hosts_metadata"] | last ) and
        ( primary_site | lower == "true" )


- name: Ensure vitam-metadata-purge-dip timer is stopped
  systemd:
    name: "vitam-metadata-purge-dip.timer"
    daemon_reload: "yes"
    enabled: "no"
    state: "stopped"
  when: ( primary_site | lower == "false" ) or
    ( inventory_hostname != groups["hosts_metadata"] | last )

- name: Ensure vitam-metadata-purge-dip timer is started
  systemd:
    name: "vitam-metadata-purge-dip.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( inventory_hostname == groups["hosts_metadata"] | last ) and
    ( primary_site | lower == "true" )
