---

- name: Install vitam-alertmanager package
  package:
    name: vitam-alertmanager
    state: latest
  register: result
  retries: "{{ packages_install_retries_number | default(1) }}"
  until: result is succeeded
  delay: "{{ packages_install_retries_delay | default(10) }}"
  notify: "prometheus-alertmanager - restart service"

#### Configuration ####
- name: Check that the alertmanager directories exist
  file:
    path: "{{ vitam_defaults.folder.root_path | default('/vitam') }}/{{ item }}/alertmanager"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"
  with_items:
    - app
    - bin
    - conf
    - lib
    - log
    - data
    - tmp
  notify: "prometheus-alertmanager - restart service"

- name: Apply prometheus alertmanager sysconfig default
  template:
    src: "alertmanager.j2"
    dest: "{{ prometheus_alertmanager_config_path }}/sysconfig/alertmanager"
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.conf_permission | default('0640') }}"
  tags:
    - update_alertmanager_configuration
  notify: "prometheus-alertmanager - restart service"

- name: Create the prometheus alertmanager configuration file
  template:
    src: "alertmanager.yml.j2"
    dest: "{{ prometheus_alertmanager_config_path }}/alertmanager.yml"
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.conf_permission | default('0640') }}"
  tags:
    - update_alertmanager_configuration
  notify:
    - "prometheus-alertmanager - restart service"

#### Consul configuration ####
- name: Ensure consul config dir is OK
  file:
    path: "{{ consul_folder_conf }}"
    state: directory
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.folder_permission | default('0750') }}"

- name: Deploy consul agent service declaration
  template:
    src: "service-componentid.json.j2"
    dest: "{{ consul_folder_conf }}/service-alertmanager.json"
    owner: "{{ vitam_defaults.users.vitam | default('vitam') }}"
    group: "{{ vitam_defaults.users.group | default('vitam') }}"
    mode: "{{ vitam_defaults.folder.conf_permission | default('0640') }}"
  tags:
    - consul_conf
    - update_alertmanager_configuration
  notify:
    - "prometheus-alertmanager - reload consul configuration"

# Ensure that the installation is complete and consul up
- meta: flush_handlers
  tags:
    - update_alertmanager_configuration

- name: Make sure vitam-alertmanager is started and enabled at boot
  service:
    name: vitam-alertmanager
    state: started
    enabled: "{{ prometheus.alertmanager.at_boot | default(service_at_boot) }}"
  tags:
    - update_alertmanager_configuration

- name: Wait for alertmanager api_port {{ prometheus.alertmanager.api_port | default(9093) }} to be open
  wait_for:
    host: "{{ ip_admin }}"
    port: "{{ prometheus.alertmanager.api_port | default(9093) }}"
    state: "started"
    timeout: "{{ vitam_defaults.services.start_timeout | default(300) }}"
