---

- name: Ensure Elasticsearch data cluster is in "green" state
  uri:
    method: GET
    url: "http://{{ elasticsearch.data.host }}:{{ elasticsearch.data.port_http }}/_cluster/health"
    body_format: "json"
  register: result
  until: result.json.status == "green"
  retries: "{{ vitam_defaults.services.status_retries_number }}"
  delay: "{{ vitam_defaults.services.status_retries_delay }}"
  delegate_to: "{{ groups['hosts_elasticsearch_data']|first }}"
  run_once: true
