---
# defaults file for common
vitam_user: vitam
vitam_group: vitam
memory_opts: -Xms512m -Xmx512m
gc_opts: "-Xloggc:{{ vitam_folder_log }}/gc.log -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=10M -XX:+PrintGCDetails -XX:+PrintGCApplicationStoppedTime"
jmx_exporter_opts: ""
java_opts: ""
java_args: ""
package_name: "vitam-{{ vitam_struct.vitam_component }}"

# Configuration par défaut du connecteur de service
# Configuration par défaut du connecteur admin
days_to_delete_logback_logfiles: 30
days_to_delete_access_local: 7
vitam_worker_capacity: "{{ ansible_processor_vcpus }}"

vitam_site_id: 1

# Trust X-SSL-CLIENT-CERT header for external api auth ? (true | false)
vitam_ssl_user_header: false
