---

- name: copy file for driver in data
  template:
    src: "fr.gouv.vitam.storage.offers.workspace.driver.DriverImpl"
    dest: "{{ vitam_folder_data }}/fr.gouv.vitam.storage.offers.workspace.driver.DriverImpl"
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.conf_permission }}"
  tags:
    - update_vitam_configuration  
  notify:
    - restart service

- name: Check that storage_archives directory exists for storage component
  file:
    path: "{{ vitam_defaults.folder.root_path }}/data/{{ vitam_component }}/storage_archives"
    state: directory
    owner: "{{ vitam_defaults.users.vitam }}"
    group: "{{ vitam_defaults.users.group }}"
    mode: "{{ vitam_defaults.folder.folder_permission }}"
  notify:
    - restart service

- name: Ensure service is started
  service:
    name: "vitam-{{ vitam_component }}"
    state: started

- name: Ensure storage accesslog backup systemd timer is enabled
  systemd:
    name: "vitam-storage-accesslog-backup.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( primary_site | lower == "true" )

- name: Ensure storage backup systemd timer is enabled
  systemd:
    name: "vitam-storage-log-backup.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( primary_site | lower == "true" )

- name: Ensure storage traceability systemd timer is enabled
  systemd:
    name: "vitam-storage-log-traceability.timer"
    daemon_reload: "yes"
    enabled: "yes"
    state: "started"
  when: ( primary_site | lower == "true" ) and
        ( inventory_hostname == groups['hosts-storage-engine'] | last )

- name: Ensure storage traceability systemd timer is stopped
  systemd:
    name: "vitam-storage-log-traceability.timer"
    daemon_reload: "yes"
    enabled: "no"
    state: "stopped"
  when: ( primary_site | lower == "false" ) or
        ( inventory_hostname != groups['hosts-storage-engine'] | last )
