---
- name: Ensure service is started 
  service:
    name: "vitam-functional-administration"
    state: started

- name: "Wait until service functional-admin is up"
  wait_for:
      host: "{{ hostvars[groups['hosts-functional-administration'][0]]['ip_admin'] }}"
      port: "{{ vitam.functional_administration.port_admin }}"
      state: "started"
      timeout: "{{ vitam_defaults.services.start_timeout }}"
  run_once: true

- name: functional-administration upgrade
  uri:
    method: POST
    status_code: 202
    force_basic_auth: yes
    user: "{{ admin_basic_auth_user }}"
    password: "{{ admin_basic_auth_password }}"
    url: "http://{{ hostvars[groups['hosts-functional-administration'][0]]['ip_admin'] }}:{{ vitam.functional_administration.port_admin }}/adminmanagement/v1/startMigration"
    headers:
      Accept: application/json
  run_once: true

##-TODO checkStatus --
## curl -X HEAD -u adminUser:adminPassword    http://localhost:18004/adminmanagement/v1/migrationStatus
##- try until 200 not found

- name: check upgrade is finished
  command: "curl -I --silent -u {{ admin_basic_auth_user }}:{{ admin_basic_auth_password }} -k -X HEAD http://{{ hostvars[groups['hosts-functional-administration'][0]]['ip_admin'] }}:{{ vitam.functional_administration.port_admin }}/adminmanagement/v1/migrationStatus"
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: "{{ nb_retries }}"
  delay: 60
  run_once: true
