---

- name: Check if defined offer is present in vitam_offers
  fail: msg="Unsupported or badly configured offer as {{ offer_conf }} is not declared in vitam_offers"
  when: offer_conf is defined and offer_conf not in vitam_offers

- name: Compute the present offers in default strategy
  set_fact:
    offers_strategy_list: "{{ offers_strategy_list + [item.name] }}"
  loop: "{{ vitam_strategy }}"

- name: Check other strategies not invalid
  fail: msg="other_strategies must contain at least one strategy when activated"
  when:
    - other_strategies is defined
    - other_strategies | type_debug != 'dict'

- name: Compute the present offers in other strategies
  set_fact:
    offers_strategy_list: "{{ offers_strategy_list + [item.name] }}"
  loop: "{{ other_strategies | default({}) | dict2items | sum(attribute='value', start=[]) }}"

- name: Check if defined offer is present in vitam_strategy or other_strategies
  fail: msg="Unsupported or badly configured offer as {{ offer_conf }} is not declared in vitam_strategy or in other_strategies"
  when: offer_conf is defined and offer_conf not in offers_strategy_list

